### ISSUE TITLE
[CHORE] Refactor Repo Structure to Allow Multiple Languages

### ISSUE THREAD

**Issue by nkpng2k** [h2oai/mlops-dai-runtimes#129]
@osery with cpp mojo's there will me more deployment strategies that implement python/alternative language to java.

Opening this issue to track thoughts here:
1. perhaps we can do something similar to what we have in DAI with a Makefile, and nest the projects into their own separate directories. e.g.
```
dai-deployment-templates
|-- Makefile
|-- python
        |-- cpp mojo project
        |-- azureml project
|-- java
        |-- original java mojo projects.
```
then we can change the java build process to dump the builds into a `build` directory... same as whatever we chose for the python side and then compile both build directories and zip them to ship. 

WDYT?

**Comment by nkpng2k** [comment]
cc @mmalohlava @achraf-mer

**Comment by osery** [comment]
Hi Nick, thanks for starting this.

Are there some alternatives? Personally, I find Make a very bad way to build projects. It does not really track dependencies so it is almost impossible to do correct incremental builds :(. The way DAI is build is imho super painful and you never know if the right thing gets actually built or not.

Gradle itself seems to have some support for Python and C++ builds:
- Python: https://github.com/linkedin/pygradle
- C++: https://docs.gradle.org/current/userguide/building_cpp_projects.html
I admit that I have never used these myself.

We use Bazel in Model Manager and build Golang and Python with it to our great happiness (it also supports Java and C++). Bazel has a rather steep learning curve, but once set up, it is really great way to build things quickly (remote caching) and consistently (tracks all dependencies).

I understand both these options are much more work, but I am really scared we could end up with thousands lines of make code that is super hard to maintain or even do correctly to start with. Wdyt? @mmalohlava

**Comment by nkpng2k** [comment]
@osery thank you for pointing out bazel and pygradle. I would be inclined, actually, to lean towards one of those. Agree, the Makefile in DAI is super unwieldy.... Wouldn't mind being forced to learn bazel.

**Comment by achraf-mer** [comment]
@nkpng2k not pushing to use a cli, just stating if something requires a cli, then the scope need to be limited, this goes for other cloud specific tools as well.

**Comment by nkpng2k** [comment]
@achraf-mer can we maybe revisit this? I think given that now we have the c++ dai mojo, it is really time to start trying to make this repo multiple language supported. WDYT?

**Comment by achraf-mer** [comment]
> @achraf-mer can we maybe revisit this? I think given that now we have the c++ dai mojo, it is really time to start trying to make this repo multiple language supported. WDYT?

Agree, if not necessary to have a common packaging tool we can work with Makefiles

**Comment by nkpng2k** [comment]
Yes I think the only thing we need to be concerned with is unified packaging for the java stuffs that is used to dai. The other stuff is entirely separated

**Comment by jakubhava** [comment]
Not planned, the python based run-times are managed in a different repo
